[package]
edition = "2021"
name = "libimage"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rapid-qoi = {version = "0.5.5"}
mpic = { git = "https://github.com/neri/mpic" }
