[package]
edition = "2021"
name = "libimage"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = {version="0.3.69"}
wasm-bindgen = {version="0.2.92"}

mpic = { path = "../../mpic" }
# mpic = {git = "https://github.com/neri/mpic"}
rapid-qoi = {version="0.6.1"}
png = {version="0.17.13"}

[dependencies.web-sys]
version = "0.3.69"
features = [
  "ImageData",
  "CanvasRenderingContext2d",
]
